export const PROPERTIES = {
  fontSize: {
    xs: 'xs',
    sm: 'sm',
    base: 'base',
    lg: 'lg',
    xl: 'xl',
    '2xl': '2xl',
    '3xl': '3xl',
    '4xl': '4xl',
    '5xl': '5xl',
    '6xl': '6xl',
    '7xl': '7xl',
    '8xl': '8xl',
  },
  fontWeight: {
    light: 'light',
    normal: 'normal',
    medium: 'medium',
    semibold: 'semibold',
    bold: 'bold',
  },
  textAlign: {
    left: 'left',
    center: 'center',
    right: 'right',
    justify: 'justify',
  },
  verticalAlign: {
    baseline: 'baseline',
    top: 'top',
    middle: 'middle',
    bottom: 'bottom',
  },
  lineHeight: {
    1: 1,
    2: 2,
    3: 3,
    4: 4,
  },
  cursor: {
    auto: 'auto',
    pointer: 'pointer',
  },
  select: {
    auto: 'auto',
    none: 'none',
    text: 'text',
    all: 'all',
  },
} as const
